// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://srtapnjbpongjmfzijjo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNydGFwbmpicG9uZ2ptZnppampvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAxNjQ3ODAsImV4cCI6MjA2NTc0MDc4MH0.CbctoR5wYhowHDdl7V6Ie1NtCABJC6zmmdopZI4pdO0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);